/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dvb_DvbPlayer */

#ifndef _Included_com_dvb_DvbPlayer
#define _Included_com_dvb_DvbPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dvb_DvbPlayer
 * Method:    start
 * Signature: (Lcom/dvb/DvbChannelNode;Z)I
 */
JNIEXPORT jint JNICALL Java_DvbPlayer_start
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_dvb_DvbPlayer
 * Method:    stop
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_DvbPlayer_stop
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_dvb_DvbPlayer
 * Method:    pauseVideo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DvbPlayer_pauseVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_dvb_DvbPlayer
 * Method:    resumeVideo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DvbPlayer_resumeVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_dvb_DvbPlayer
 * Method:    switchAudioTrack
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DvbPlayer_switchAudioTrack
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dvb_DvbPlayer
 * Method:    switchAudioChannel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DvbPlayer_switchAudioChannel
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_DvbPlayer_configNim
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_DvbPlayer_showlogo
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_DvbPlayer_setPos
  (JNIEnv *env, jobject obj, jint, jint, jint, jint);

JNIEXPORT jint JNICALL Java_DvbPlayer_GetVol
(JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_DvbPlayer_SetVol
(JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_DvbPlayer_GetVolMute
(JNIEnv *env , jobject obj);

JNIEXPORT jint JNICALL Java_DvbPlayer_SetVolMute
(JNIEnv *env, jobject obj, jint mute);

#ifdef __cplusplus
}
#endif
#endif
