/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dvb_DvbEpg */

#ifndef _Included_com_dvb_DvbEpg
#define _Included_com_dvb_DvbEpg
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dvb_DvbEpg_PRESENT_EVENT
#define com_dvb_DvbEpg_PRESENT_EVENT 0L
#undef com_dvb_DvbEpg_FOLLOWING_EVENT
#define com_dvb_DvbEpg_FOLLOWING_EVENT 1L
#undef com_dvb_DvbEpg_SCHEDULE_EVENT
#define com_dvb_DvbEpg_SCHEDULE_EVENT 2L
/*
 * Class:     com_dvb_DvbEpg
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dvb_DvbEpg_initIDs
  (JNIEnv *, jclass);


/*
 * Class:     com_dvb_DvbEpg
 * Method:    getStremTime
 * Signature: (I)Lcom/dvb/DvbTime
 */
JNIEXPORT jobject JNICALL Java_com_dvb_DvbEpg_getStreamTime
  (JNIEnv *, jclass, jint);


/*
 * Class:     com_dvb_DvbEpg
 * Method:    setActiveService
 * Signature: ([Lcom/dvb/DvbChannelNode;)I
 */
JNIEXPORT jint JNICALL Java_com_dvb_DvbEpg_setActiveService
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_dvb_DvbEpg
 * Method:    delService
 * Signature: (Lcom/dvb/DvbChannelNode;)I
 */
JNIEXPORT jint JNICALL Java_com_dvb_DvbEpg_delService
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dvb_DvbEpg
 * Method:    getPresentEvent
 * Signature: (Lcom/dvb/DvbChannelNode;Z)Lcom/dvb/DvbEpgEvent;
 */
JNIEXPORT jobject JNICALL Java_com_dvb_DvbEpg_getPresentEvent
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_dvb_DvbEpg
 * Method:    getFollowingEvent
 * Signature: (Lcom/dvb/DvbChannelNode;Z)Lcom/dvb/DvbEpgEvent;
 */
JNIEXPORT jobject JNICALL Java_com_dvb_DvbEpg_getFollowingEvent
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_dvb_DvbEpg
 * Method:    loadScheduleEvent
 * Signature: (Lcom/dvb/DvbChannelNode;Lcom/dvb/DvbTime;Lcom/dvb/DvbTime;Z)I
 */
JNIEXPORT jint JNICALL Java_com_dvb_DvbEpg_loadScheduleEvent
  (JNIEnv *, jobject, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_dvb_DvbEpg
 * Method:    getScheduleEvent
 * Signature: (I)Lcom/dvb/DvbEpgEvent;
 */
JNIEXPORT jobject JNICALL Java_com_dvb_DvbEpg_getScheduleEvent
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
