/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dvb_DvbChannel */

#ifndef _Included_com_dvb_DvbSystemSetting
#define _Included_com_dvb_DvbSystemSetting
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_dvb_DvbSystemSetting
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DvbSystemSetting_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbSystemSetting
 * Method:    setAspect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbSystemSetting_setAspect
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_dvb_DvbSystemSetting
 * Method:    setBrightness
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbSystemSetting_setBrightness
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_dvb_DvbSystemSetting
 * Method:    setSndChn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbSystemSetting_setSndChn
  (JNIEnv *, jclass, jint);


#ifdef __cplusplus
}
#endif
#endif
