/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dvb_DvbSystem */

#ifndef _Included_com_dvb_DvbSystem
#define _Included_com_dvb_DvbSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dvb_DvbSystem
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ali_dvbdemo_DvbSystem_init
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbSystem
 * Method:    exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ali_dvbdemo_DvbSystem_exit
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbSystem
 * Method:    loadDefault
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DvbSystem_loadDefault
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbSystem
 * Method:    getboardType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ali_dvbdemo_DvbSystem_getboardType
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbSystem
 * Method:    LockFreq
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ali_dvbdemo_DvbSystem_LockFreq
  (JNIEnv *, jclass, jint, jint);


/*
 * Class:     com_dvb_DvbSystem
 * Method:    getTunerLock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ali_dvbdemo_DvbSystem_getTunerLock
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbSystem
 * Method:    getTunerSNR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ali_dvbdemo_DvbSystem_getTunerSNR
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbSystem
 * Method:    getTunerAGC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ali_dvbdemo_DvbSystem_getTunerAGC
  (JNIEnv *, jclass);

 JNIEXPORT jint JNICALL Java_com_DvbPanelShow
 (JNIEnv *, jclass , jstring , jint);

#ifdef __cplusplus
}
#endif
#endif
