/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dvb_DvbChannel */

#ifndef _Included_com_dvb_DvbSatellite
#define _Included_com_dvb_DvbSatellite
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_dvb_DvbSatellite
 * Method:    initIDs
 * Signature: (Lcom/ali/dvbdemo/DVBSatelliteNode;)V
 */
JNIEXPORT void JNICALL Java_DvbSatellite_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbSatellite
 * Method:    loadSatelliteNodes
 * Signature: ()[Lcom/dvb/DVBSatelliteNode;
 */
JNIEXPORT jobjectArray JNICALL Java_DvbSatellite_loadSatelliteNodes
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbSatellite
 * Method:    updateSatellite
 * Signature: (Lcom/dvb/DVBSatelliteNode;)I
 */
JNIEXPORT jint JNICALL Java_DvbSatellite_updateSatellite
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_dvb_DvbSatellite
 * Method:    loadTpNodes
 * Signature: (I)[Lcom/alitech/dvb/DvbTpNode;
 */
JNIEXPORT jobjectArray JNICALL Java_DvbSatellite_loadTpNodes
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_dvb_DvbSatellite
 * Method:    updateTpNode
 * Signature: (Lcom/alitech/dvb/DvbTpNode;)I
 */
JNIEXPORT jint JNICALL Java_DvbSatellite_updateTpNode
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_dvb_DvbSatellite
 * Method:    deleteSatellite
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbSatellite_deleteSatellite
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_dvb_DvbSatellite
 * Method:    deleteTpNode
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbSatellite_deleteTpNode
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
