/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DvbUdrm */

#ifndef _Included_DvbUdrm
#define _Included_DvbUdrm
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_DvbUdrm_getinfo
	(JNIEnv *pJNIEnv, jobject obj);

/*
 * Class:     DvbUdrm
 * Method:    getUdrmPpcNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DvbUdrm_getUdrmPpcNum
  (JNIEnv *, jobject);

/*
 * Class:     DvbUdrm
 * Method:    getUdrmPpcId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DvbUdrm_getUdrmPpcId
  (JNIEnv *, jobject, jint);

/*
 * Class:     DvbUdrm
 * Method:    getUdrmEmailInfo
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_DvbUdrm_getUdrmEmailInfo
  (JNIEnv *, jobject);

/*
 * Class:     DvbUdrm
 * Method:    deleteUdrmEmail
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbUdrm_deleteUdrmEmail
  (JNIEnv *, jobject, jint);

/*
 * Class:     DvbUdrm
 * Method:    setUdrmWatchClass
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbUdrm_setUdrmWatchClass
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     DvbUdrm
 * Method:    getUdrmWatchClass
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DvbUdrm_getUdrmWatchClass
  (JNIEnv *, jobject);

/*
 * Class:     DvbUdrm
 * Method:    setUdrmPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbUdrm_setUdrmPassword
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     DvbUdrm
 * Method:    checkUdrmPassword
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_DvbUdrm_checkUdrmPassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DvbUdrm
 * Method:    getUdrmInfo
 * Signature: ()Lcom/alitech/dvb/DvbUdrmInfo;
 */
JNIEXPORT jobject JNICALL Java_DvbUdrm_getUdrmInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
