/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dvb_DvbChannel */

#ifndef _Included_com_dvb_DvbChannel
#define _Included_com_dvb_DvbChannel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dvb_DvbChannel_CHAN_MODE_MASK
#define com_dvb_DvbChannel_CHAN_MODE_MASK 2130706432L
#undef com_dvb_DvbChannel_CHAN_GROUP_MASK
#define com_dvb_DvbChannel_CHAN_GROUP_MASK 16711680L
#undef com_dvb_DvbChannel_CHAN_GROUP_PARAM_MASK
#define com_dvb_DvbChannel_CHAN_GROUP_PARAM_MASK 65535L
#undef com_dvb_DvbChannel_CHAN_GROUP_ALL
#define com_dvb_DvbChannel_CHAN_GROUP_ALL 0L
#undef com_dvb_DvbChannel_CHAN_GROUP_TVRADIO
#define com_dvb_DvbChannel_CHAN_GROUP_TVRADIO 65536L
#undef com_dvb_DvbChannel_CHAN_GROUP_NVOD
#define com_dvb_DvbChannel_CHAN_GROUP_NVOD 131072L
#undef com_dvb_DvbChannel_CHAN_GROUP_DATA
#define com_dvb_DvbChannel_CHAN_GROUP_DATA 196608L
#undef com_dvb_DvbChannel_CHAN_GROUP_LOCAL
#define com_dvb_DvbChannel_CHAN_GROUP_LOCAL 262144L
#undef com_dvb_DvbChannel_CHAN_GROUP_FAV
#define com_dvb_DvbChannel_CHAN_GROUP_FAV 327680L
#undef com_dvb_DvbChannel_CHAN_GROUP_FAVALL
#define com_dvb_DvbChannel_CHAN_GROUP_FAVALL 393216L
#undef com_dvb_DvbChannel_CHAN_MODE_RADIO
#define com_dvb_DvbChannel_CHAN_MODE_RADIO 0L
#undef com_dvb_DvbChannel_CHAN_MODE_TV
#define com_dvb_DvbChannel_CHAN_MODE_TV 16777216L
#undef com_dvb_DvbChannel_CHAN_MODE_TVRADIO
#define com_dvb_DvbChannel_CHAN_MODE_TVRADIO 33554432L
/*
 * Class:     com_dvb_DvbChannel
 * Method:    initIDs
 * Signature: (Lcom/ali/dvbdemo/DvbChannelNode;)V
 */
JNIEXPORT void JNICALL Java_DvbChannel_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_dvb_DvbChannel
 * Method:    loadChannels
 * Signature: (I)[Lcom/dvb/DvbChannelNode;
 */
JNIEXPORT jobjectArray JNICALL Java_DvbChannel_loadChannels
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_dvb_DvbChannel
 * Method:    updateChannel
 * Signature: (Lcom/dvb/DvbChannelNode;)I
 */
JNIEXPORT jint JNICALL Java_DvbChannel_updateChannel
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
