/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dvb_DvbSystem */

#ifndef _Included_com_property
#define _Included_com_property
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_DvbProperty_getSS(JNIEnv *env, jobject clazz,
                                      jstring keyJ, jstring defJ);

JNIEXPORT jint JNICALL Java_DvbProperty_get_int(JNIEnv *env, jobject clazz,
                                      jstring keyJ, jint defJ);

JNIEXPORT void JNICALL Java_DvbProperty_set(JNIEnv *env, jobject clazz,
                                      jstring keyJ, jstring valJ);

#ifdef __cplusplus
}
#endif
#endif
