
#ifndef _ALI_MAGIC_NUM_H_
#define _ALI_MAGIC_NUM_H_

#define ALI_MAGIC_BASE			0x50

#define ALI_IMAGE_MAGIC	(ALI_MAGIC_BASE + 0)
#define ALI_AVSYNC_MAGIC	(ALI_MAGIC_BASE + 1)
#define ALI_CE_MAGIC			(ALI_MAGIC_BASE + 2)
#define ALI_DSC_MAGIC		(ALI_MAGIC_BASE + 3)
#define ALI_TRNG_MAGIC		(ALI_MAGIC_BASE + 4)
#define ALI_AUDIO_MAGIC		(ALI_MAGIC_BASE + 5)

#endif

